services:
  postgres:
    image: postgres:17
    restart: always
    container_name: senlatask10
    environment:
      POSTGRES_DB: "senlatask10"
      POSTGRES_USER: "testpguser"
      POSTGRES_PASSWORD: "testpgpwd"
    ports:
      - "5432:5432"